[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.offset]
y = 1

[scrolling]
# Scrollback for 10000 lines
history = 10000
multiplier = 3

# Launch tmux with zsh by default
# Attach to tmux session if exists, otherwise create one
[shell]
args = ["-l", "-c", "/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux -u"]
program = "/bin/zsh"

[window]
opacity = 0.95
# Enable alt key as meta key for neovim copilot
option_as_alt = "OnlyLeft"

# Bigger display
[window.dimensions]
columns = 180
lines = 50

# Add padding like MacOS window style
[window.padding]
x = 8
y = 4
